version: "3.3"
services:
  application:
    build: ./application/
    ports:
      - "8080:8080"
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - type: bind 
        source: ./prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
